### ISSUE TITLE
Unable to launch DesktopLauncher

### ISSUE THREAD

**Issue by jjarmolowicz** [jjarmolowicz/gnixob#1]
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load file: badlogic.jpg
	at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:149)
	at com.badlogic.gdx.graphics.TextureData$Factory.loadFromFile(TextureData.java:98)
	at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:122)
	at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:114)
	at fun.game.Gnixob.create(Gnixob.java:18)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:149)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: File not found: badlogic.jpg (Internal)
	at com.badlogic.gdx.files.FileHandle.read(FileHandle.java:142)
	at com.badlogic.gdx.files.FileHandle.readBytes(FileHandle.java:228)
	at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:146)
	... 6 more

**Comment by jjarmolowicz** [comment]
z intelijeju

**Comment by jjarmolowicz** [comment]
RTFM !
